### ISSUE TITLE
zuus and zeus foulder missing zeus foulder

### ISSUE THREAD

**Issue by Kreegola** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#26]
zuus uses 2 foulder for items zeus foulder is missing so no weapon like Righteous Thunderbolt can be stored correctly

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
It's because there is no default weapon slot for zeus. Try searching Zeus's Weapon at items_game.txt, it has NO default item file defined on it. So it can't be override.

If you checked **pak01_dir.vpk/models/heroes/** folder, there is no zeus folder out there(maybe you have a custom mod that has a folder named like that).
