### ISSUE TITLE
I don't know how to make a pull request, but I would like to see more option for miscellaneous effects

### ISSUE THREAD

**Issue by Kreegola** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#32]
like I know there are more items effect and fogs ects.
would be cool to have them added and knowing how to do it manualy if not possible.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Due to the complexity of the source code, Code Pulling is hard to implement. I didn't actually written the source code in a way that it is community friendly. But maybe in the future when I completely rewritten this tool's source code, I will keep thay in mind.

But you can suggest what misc you would like to see on the future updates and I can answer whether if its possible or not.
