### ISSUE TITLE
im just asking.. its not about found an issue

### ISSUE THREAD

**Issue by dikafarabian** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#4]
first of all,,im so sorry for my bad english

is that possible to put items_game.txt to dota2 directory?
im try to delete all the folder on the pak01_dir except "script" folder,,
they work perfect on offline mode,,
so,, this is why im asking.
will it work perfectly on online mode if i put the modified items_game.txt to dota2 directory, and not on the mod folder
thank you very much dude,, im enjoying your app tool, and love it so much

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
> is that possible to put items_game.txt to dota2 directory?

As far as I know, items_game.txt needs to be inside pak01_dir.vpk archive. So you can either:
1. directly put it inside the REAL pak01_dir.vpk found at **dota 2 beta/game/dota/pak01_dir.vpk**
2. Override the pak01_dir.vpk by creating a fake pak01_dir.vpk (Called **Shutnik Method**).

> will it work perfectly on online mode if i put the modified items_game.txt to dota2 directory, and not on the mod folder

As far as I know, putting the items_game.txt inside the Dota 2 Directory(Inside **dota 2 beta/game/dota/pak01_dir.vpk**) will still make some cosmetic item to not appear when playing PVP. I tried it myself and that happens that is why I decided to also override the default .vmdl,.vpcf,vmat files

> im try to delete all the folder on the pak01_dir except "script" folder,,
> they work perfect on offline mode,,
> so,, this is why im asking.

If I understand you correctly, You want the customly generated pak01_dir.vpk of this script to ONLY have "script\items\items_game.txt" inside it and nothing else?

DOTA2 MOD Master by default Generates multiple files like Text-Scripts,Compressed Model(.vmdl_c),Particle Effect(.vpcf_c),Material(.vmat_c),SoundEvent(.vsndevts_c) files. So you need to do it yourself manually since there is no option for only generating items_game.txt and nothing else.

Here is how you will do it:

1. Everytime you Inject a MOD, a pak01_dir folder is generated at "ToolDirectory\Plugins\VPKCREATOR\" Folder.
2. Inside pak01_dir folder, delete all folders **_EXCEPT this two folders and its files inside_**, they are required even at offline games. Take not
- scripts
- soundevents
3. inside the "VPKCREATOR" Folder, left click then drag the "pak01_dir" folder towards the "vpk.exe", a command prompt will pop up and wait for it to finish.
4. When the command prompt is gone, a pak01_dir.vpk will be created at the same directory.
5. Put the pak01_dir.vpk at "steam/steamapps/common/dota 2 beta/game/Aldrin_Mods/" Folder
6. Done

> thank you very much dude,, im enjoying your app tool, and love it so much

Thank you for using the Tool, it is not always good, since it is just a fragment of how I mod dota 2 and I'm not expert myself.
