### ISSUE TITLE
Aldrin's custom gameinfo.gi doesnt work. + 1 question

### ISSUE THREAD

**Issue by quishyy** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#43]
I tried to install mods through this tool, and in game theres a vac message. Amir4an's gameinfo.gi works fine.
In addition i would like to know, how does arcana effects work if i didnt installed scripts? WR arcana and some of immortal items have particles and effects, even though i didnt installed scripts, just models and particles
Still, thanks for your awesome work

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
- What GameMode did you play thay receives a VAC Notification? Does it show up on Classic or Ranked?
- Have you tried using a fresh gameinfo.ig by steam > verify DOTA2 file integrity?

Arcana particle effects works exactly the same as normal cosmetic item's particle effects, they are attached on a specific bone within the hero's mesh. For us modders to use the particle effects, you either:
1) define a new particle file name for each custom/arcana particle effect that is attached inside the hero model file(you'll be modifying .vmdl_c elements) and then replace the custom/arcana particle file name into this newly defined particle file name. (Note: I don't do this since it's so impractical).
2. Rename the custom/arcana particle file name into the default particle file name, and then replace the default particle file into our custom particle effect.

**Comment by quishyy** [comment]
> - What GameMode did you play thay receives a VAC Notification? Does it show up on Classic or Ranked?
> - Have you tried using a fresh gameinfo.ig by steam > verify DOTA2 file integrity?
> 
> Arcana particle effects works exactly the same as normal cosmetic item's particle effects, they are attached on a specific bone within the hero's mesh. For us modders to use the particle effects, you either:
> 1) define a new particle file name for each custom/arcana particle effect that is attached inside the hero model file(you'll be modifying .vmdl_c elements) and then replace the custom/arcana particle file name into this newly defined particle file name. (Note: I don't do this since it's so impractical).
> 2. Rename the custom/arcana particle file name into the default particle file name, and then replace the default particle file into our custom particle effect.

I receive that warning for both classic and ranked. Default gameinfo.gi works but theres no mods. I'm just saying that your gameinfo.gi is detected. I'm currently using Amir4an's gameinfo.gi. Thanks for reply

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
It works fine for me though... What's your OS?

Also, upload the 2 versions of gameinfo.gi so that I can analyze what's wrong:
- fresh gameinfo.gi(default by DOTA2) before using DOTA2 MOD Master
- gameinfo.gi after modding with DOTA2 MOD Master

**Comment by quishyy** [comment]
> It works fine for me though... What's your OS?
> 
> Also, upload the 2 versions of gameinfo.gi so that I can analyze what's wrong:
> - fresh gameinfo.gi(default by DOTA2) before using DOTA2 MOD Master
> - gameinfo.gi after modding with DOTA2 MOD Master

Windows 10 Professional, 64bit. I can't send you right now, i'm in school. I'll try to send you files in 2 hours
