### ISSUE TITLE
Can't get ability effects item slots?

### ISSUE THREAD

**Issue by Heporis** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#94]
I don't like some immortal items, and just want to apply it's ability effects.

**Comment by quishyy** [comment]
Hi, you can do that via changing scripts by yourself, or making custom skins in the tool itself (check github guids and previous closed issues) and the easy way, stick to either injector-changers or already done mod-packs. This tool is best used if you know what're you doing, and if you also have required skill in changing things manually. I can recommend you overplus for 2-3 dollars per month (changer that injects in your game, it's rather safe and always has been, you can be banned only for smurf accs by valve, not changer), or you can use dota2skinchanger, site where for 3-5 dollars per month you get vip subscription with a huge variation of skins, including a few modded ones. It seems like Aldrin has finished working on this tool, it works and you can change things by yourself if something required that tool cannot do. 
edit: In addition to the last sentences, probably no one will help you with this tool, it's very niche and limited, you need to do workarounds and fixes by yourself, such as missing cosmetics because there's no default model in slot etc.

**Comment by Heporis** [comment]
Thank you! I have tried overplus, but it doesn't support ARCADE.
